version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        - "oleg.gr@outlook.com"
    command: /usr/src/app/Scripts/dockerstart.sh
    volumes:
      - ./Logs:/usr/src/app/Logs
    ports:
      - 8081:8081
    links:
      - postgresql:postgresql_domain
    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    container_name: postgres
    image: postgres:12.5-alpine
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=database
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: "exit 0"
