version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_PATH: $PROJECT_PATH
      labels:
        - "oleg.gr@outlook.com"
    command: ${PROJECT_PATH}Scripts/dockerstart.sh
    volumes:
      - ./Logs:${PROJECT_PATH}Logs
    ports:
      - 8081:8081
    env_file: .env
    links:
      - mariadb:db_domain
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    image: mariadb:10.5
    volumes:
      - dbvolume:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: $MARIA_DB
      MYSQL_USER: $MARIA_USERNAME
      MYSQL_PASSWORD: $MARIA_PASSWORD
      MYSQL_ROOT_PASSWORD: $MARIA_PASSWORD

volumes:
  dbvolume: